manifestVersion = 0

[package]
  type = "mod"
  name = "inmis"
  description = "I need more inventory space!"
  version = "2.4.0"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "1.18-rc3"
  fabric = "0.12.5"

[dependencies]
  fabric = "0.43.1+1.18"

[dev]
  buildCommand = "./gradlew build"
